# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "2025 Nordic-RSE conference"
email: "secretary@nordic-rse.org"
description: "2025 Nordic-RSE conference "
baseurl: "/nrse2025"
url: "https://nordic-rse.org/nrse2025"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Nordic-RSE"
organizerAlternateName: "Nordic-RSE"
organizerDescription: "Nordic-RSE"
organizerEmail: "secretary@nordic-rse.org"
organizerLogo: "/img/sprites/logo.png"
organizerLink: "http://nordic-rse.org"

# Head
metaKeywords: "event, RSE, open-source, open-science, HPC"
twitterAccount: ""
socialImageSrcGooglePlus: ""
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: 'Home'}
 - {permalink: "/#cfp", text: "Call for contributions"}
 - {permalink: "/#registration", text: "Registration"}
 - {permalink: "/#venue", text: "Venue"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.svg"
heroTitle: "Nordic-RSE <typeout> 2025"
eventDate: "May 20-21, 2025"
typeoutTextValues: '"", "Gothenburg", "Sweden"'
typeoutFallback: "Gothenburg"
# heroButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Welcome!"
aboutBlock:
 - {title: "Share experiences", image: "share.png", text: "Share your experiences and ideas with other alike cool people." }
 - {title: "Be social", image: "community.png", text: "Have fun and play some games with other like-minded people!" }
 - {title: "Learn Tools", image: "share.png", text: "Learn new tools to boost your productivity!"}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "University of Gothenburg"
eventLocationLink: "https://www.gu.se/en"
eventStreetAddress: "Renströmsgatan 6"
eventAddressLocality: "Gothenburg"
eventAddressLocalityRegion: ""
eventPostalCode: "40530"
eventAddressCountry: "Sweden"
eventStartTime: "2025-05-20"
eventDoorTime: "09:00"
eventEndTime: "2025-21-21"
eventPlaceCoordinates: "57.694991549472945, 11.98507934052062"
mapCenterCoordinates: "57.694991549472945, 11.98507934052062"
mapMobileCenterCoordinates: "57.694991549472945, 11.98507934052062"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueBigImageCredits: "Natonato, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons"
venueSmallImage1: "venue_1.jpg"
venueSmallImage1Credits: "Gunnar Jönsson (taken from: https://www.gu.se/studera/hitta-utbildning/vara-lokaler-pa-humanisten)"
venueSmallImage2: "venue_2.jpg"
venueSmallImage2Credits: "Jessica Oscarsson (taken from: https://www.gu.se/nyheter/da-inviger-vi-nya-humanisten)"
venueTitle: "University of Gothenburg"
venueFeatures: ["Renströmsgatan 6", "Gothenburg, Sweden"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Registration"
ticketsInfo: 'Tickets grant access to all sessions, lunch on both day and one conference dinner. Accommodation is NOT included in the ticket price. If you would like to apply for a waiver, please send an email to <a href="mailto:secretary@nordic-rse.org">secretary@nordic-rse.org</a>, decision will be made on a per-case basis.'
ticketsOffers:

 -
  name: "General admission"
  price: "900"
  priceCurrency: "SEK"
  featured: true
  ticketsNumber: ""
  buyButtonLink: https://www.tickettailor.com/checkout/new-session/id/5204835/chk/bca4/?ref=website_widget&show_search_filter=true&show_date_filter=true&show_sort=true)
  buyButtonText: "Buy Now"
  ticketContentList: ["Includes access to all conference events", "Includes lunch on both days", "Includes an informal conference dinner on the first day"]
  validFrom: "2025-01-24T10:00"
  validThrough: "2025-04-30T23:45"

# Footer
socialLinks:
#  - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
#  - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
#  - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
#  - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
#  -
#   title: "Links"
#   links:
#    - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
#    - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:secretary@nordic-rse.org", text: "secretary@nordic-rse.org"}
 -
  title: "FAQ"
  links:
   - {link: "https://nordic-rse.org/about/code-of-conduct/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "57.694991549472945, 11.98507934052062"
logisticsMapMobileCenterCoordinates: "57.694991549472945, 11.98507934052062"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "venue_0.jpg"
directionDetailsTitle: "Get around Gothenburg"
directionDetailsCards:
 - {title: "From the Airport", information: 'Gothenburg Landvetter Airport. Between the airport and the University of Gothenburg it takes about 30-45 minutes, however in some days and times traffic can be an issue on the way. Therefore we suggest planning for an hour of travel. From the exit of the terminal, you should see signs for the bus from the airport, called Flygbussarna. The signs bear the logo of the company, which is a rainbow. The stop of the bus is at the exit from the airport, just on the left. Buy a ticket before getting on the bus, you can do this online (flygbussarna.se) or at the automatic machine by the door. Travel to the stop Korsvägen, and then follow directions from Public Transit. This leg should take about 20 minutes in ideal conditions. Note: the Flygbussarna network is not part of the public transports (Västtrafik) network, so tickets bought for one are not valid for the other!'}
 - {title: "From the Train Station", information: 'Get out from the South exit (to the left with respect to the arrival direction of trains). Once you have crossed the road, you will find yourself on a big square, to the left of you there is a big hotel called Clarion Hotel. Cross the square straight and you will find the tram stop Centralstationen. To go to the University, you can take either Tram 2 from platform B or Tram 4 from platform C, to the station Korsvägen. More info about public transportation below.'
 - {title: "Public Transit", information: 'In Gothenburg, it is quite easy to get around using either busses or trams. To travel by tram, you will need a ticket which you can buy with the app Västtrafik or by tapping your payment card on the dedicated readers (this second option is only available in Zone A). Unless you are planning a trip outside of the city, all your travels will be done with a zone A ticket. It is possible to buy physical tickets at selected places and on some trams, but it is more expensive than buying in the app. The closest tram stop to the University where the conference is hosted is called Korsvägen. It is a major centre of transportation dispatch, and from there you can take trams that go more or less everywhere in town. From Korsvägen, you will have to climb up the hill to get to the Department. Follow indications on the map.'}
 - {title: "Hotels", information: 'The Nordic RSE conference has no special prices with the local hotels. Some of the hotels close to the department are the Comfort Hotel Panorama, the Poseidon, Hotell Heden, Hotell City Avenyn, Hotel Vasa, Scandic Rubinen or Scandic Opalen. But more can be found on Booking.com or other websites. In general, Gothenburg is not a big city, and much of it is walkable distance. Feel free to reach out for more information.'}
directionDetailsWideCards:
 -
  title: "Questions"
  subCards:
  -
    title: "Hotels"
    links:
      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
  -
   title: "Registration"
   links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
  -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
